<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-03-19T06:28:29 IST" name="SubmitOrderSuite" finished-at="2025-03-19T06:29:38 IST" duration-ms="68957">
    <groups>
      <group name="ErrorHandling">
        <method signature="Error_Validation_Test.login_error_Validation()[pri:0, instance:com.test.Error_Validation_Test@2a4fb17b]" name="login_error_Validation" class="com.test.Error_Validation_Test"/>
        <method signature="Error_Validation_Test.product_error_Validation()[pri:0, instance:com.test.Error_Validation_Test@2a4fb17b]" name="product_error_Validation" class="com.test.Error_Validation_Test"/>
      </group> <!-- ErrorHandling -->
    </groups>
    <test started-at="2025-03-19T06:28:29 IST" name="SubmitOrderTest" finished-at="2025-03-19T06:28:51 IST" duration-ms="21896">
      <class name="com.test.SubmitOrderTest_Browser">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:com.test.SubmitOrderTest_Browser@359f7cdf]" started-at="2025-03-19T06:28:29 IST" name="launchApplication" finished-at="2025-03-19T06:28:42 IST" duration-ms="12812" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrderTest()[pri:0, instance:com.test.SubmitOrderTest_Browser@359f7cdf]" started-at="2025-03-19T06:28:42 IST" name="submitOrderTest" finished-at="2025-03-19T06:28:50 IST" duration-ms="8037" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrderTest -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.test.SubmitOrderTest_Browser@359f7cdf]" started-at="2025-03-19T06:28:50 IST" name="teardown" finished-at="2025-03-19T06:28:51 IST" duration-ms="1004" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.test.SubmitOrderTest_Browser -->
    </test> <!-- SubmitOrderTest -->
    <test started-at="2025-03-19T06:28:29 IST" name="ErrorValidationTest" finished-at="2025-03-19T06:29:38 IST" duration-ms="68957">
      <class name="com.test.Error_Validation_Test">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:com.test.Error_Validation_Test@2a4fb17b]" started-at="2025-03-19T06:28:29 IST" name="launchApplication" finished-at="2025-03-19T06:28:59 IST" duration-ms="30300" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="login_error_Validation()[pri:0, instance:com.test.Error_Validation_Test@2a4fb17b]" started-at="2025-03-19T06:28:59 IST" name="login_error_Validation" finished-at="2025-03-19T06:29:01 IST" duration-ms="1578" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect or password.] but found [Incorrect email or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect or password.] but found [Incorrect email or password.]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at com.test.Error_Validation_Test.login_error_Validation(Error_Validation_Test.java:26)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_error_Validation -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.test.Error_Validation_Test@2a4fb17b]" started-at="2025-03-19T06:29:01 IST" name="teardown" finished-at="2025-03-19T06:29:02 IST" duration-ms="920" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:com.test.Error_Validation_Test@2a4fb17b]" started-at="2025-03-19T06:29:02 IST" name="launchApplication" finished-at="2025-03-19T06:29:30 IST" duration-ms="28105" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="product_error_Validation()[pri:0, instance:com.test.Error_Validation_Test@2a4fb17b]" started-at="2025-03-19T06:29:30 IST" name="product_error_Validation" finished-at="2025-03-19T06:29:37 IST" duration-ms="6983" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- product_error_Validation -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.test.Error_Validation_Test@2a4fb17b]" started-at="2025-03-19T06:29:37 IST" name="teardown" finished-at="2025-03-19T06:29:38 IST" duration-ms="1033" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.test.Error_Validation_Test -->
    </test> <!-- ErrorValidationTest -->
  </suite> <!-- SubmitOrderSuite -->
</testng-results>
